import mongoose from "mongoose";
import config from "./config";
import User from "./models/User";
import Patient from "./models/Patient";
import {randomUUID} from "crypto";
import MedicalRecord from "./models/MedicalRecord";
import Treatment from "./models/Treatment";

const run= async () => {
  await mongoose.connect(config.db);
  const db = mongoose.connection;

  try {
    await db.dropCollection("users");
    await db.dropCollection("patients");
    await db.dropCollection("medicalrecords");
    await db.dropCollection("treatments");
  } catch (e) {
      console.log("Collections were not presents, skipping drop ");
  }

  const [doc_1, doc_2] = await User.create(
      {
          username: "admin",
          password: "admin",
          role: "admin",
          name: "Admin",
          specialization: "admin",
          token: randomUUID(),
          avatar: "",
      },
      {
          username: "doc_asan",
          password: "123",
          role: "doctor",
          name: "Асан Асанов",
          specialization: "Кардиолог",
          token: randomUUID(),
          avatar: "fixtures/doc_1.jpeg",
      },
      {
          username: "doc_uson",
          password: "123",
          role: "doctor",
          name: "Усон Усонов",
          specialization: "Травматолог",
          token: randomUUID(),
          avatar: "fixtures/doc_2.jpeg",
      },
  );
    const [patient1, patient2, patient3] = await Patient.create(
        {
            firstName: "Айжан",
            lastName: "Токтогулова",
            middleName: "Эсеновна",
            dateOfBirth: new Date("1990-04-15"),
            gender: "female",
            address: "г. Бишкек, ул. Абдрахманова 55",
            phone: "+996700123456",
            email: "aizhan@example.com",
            insuranceNumber: "INS123456",
            bloodType: "A+",
            allergies: "Пыльца",
            chronicDiseases: "Гипертония",
        },
        {
            firstName: "Нурсултан",
            lastName: "Исмаилов",
            middleName: "Канатович",
            dateOfBirth: new Date("1985-09-30"),
            gender: "male",
            address: "г. Ош, ул. Ленина 12",
            phone: "+996555654321",
            email: "nursultan@example.com",
            insuranceNumber: "INS654321",
            bloodType: "B-",
            allergies: "Нет",
            chronicDiseases: "Астма",
        },
        {
            firstName: "Жылдыз",
            lastName: "Садыкова",
            middleName: "Мирлановна",
            dateOfBirth: new Date("2000-01-05"),
            gender: "female",
            address: "г. Кара-Балта, ул. Молодежная 7",
            phone: "+996770789012",
            email: "jyldyz@example.com",
            insuranceNumber: "INS789012",
            bloodType: "O+",
            allergies: "Лактоза",
            chronicDiseases: "Нет",
        },
        {
            firstName: "Айгуль",
            lastName: "Токтогулова",
            middleName: "Бакытовна",
            dateOfBirth: new Date("1978-03-15"),
            gender: "female",
            address: "г. Бишкек, мкр. Джал 23-45",
            phone: "+996312987654",
            email: "aigul.toktogulova@gmail.com",
            insuranceNumber: "INS789123",
            bloodType: "A+",
            allergies: "Пенициллин, орехи",
            chronicDiseases: "Гипертония",
        },
        {
            firstName: "Темирлан",
            lastName: "Омуралиев",
            middleName: "Асанович",
            dateOfBirth: new Date("1992-11-22"),
            gender: "male",
            address: "г. Каракол, ул. Токтогула 87",
            phone: "+996558741239",
            email: "temirlan.omur@mail.ru",
            insuranceNumber: "INS456789",
            bloodType: "O+",
            allergies: "Нет",
            chronicDiseases: "Нет",
        },
        {
            firstName: "Жамила",
            lastName: "Сулайманова",
            middleName: "Тургуновна",
            dateOfBirth: new Date("1965-07-08"),
            gender: "female",
            address: "г. Талас, ул. Фрунзе 34",
            phone: "+996552369874",
            email: "zhamila65@inbox.ru",
            insuranceNumber: "INS321654",
            bloodType: "AB+",
            allergies: "Йод, рыба",
            chronicDiseases: "Диабет 2 типа",
        },
        {
            firstName: "Марат",
            lastName: "Жунусов",
            middleName: "Эрикович",
            dateOfBirth: new Date("1989-12-03"),
            gender: "male",
            address: "г. Нарын, ул. Ленина 156",
            phone: "+996557123456",
            email: "marat.zhunusov@yandex.com",
            insuranceNumber: "INS987456",
            bloodType: "A-",
            allergies: "Пыльца растений",
            chronicDiseases: "Аллергический ринит",
        },
        {
            firstName: "Гульнара",
            lastName: "Абдиева",
            middleName: "Жолдошевна",
            dateOfBirth: new Date("1981-05-20"),
            gender: "female",
            address: "г. Джалал-Абад, мкр. Сазонов 12-8",
            phone: "+996553987456",
            email: "gulnara.abdieva@gmail.com",
            insuranceNumber: "INS147258",
            bloodType: "B+",
            allergies: "Нет",
            chronicDiseases: "Мигрень",
        },
        {
            firstName: "Салтанат",
            lastName: "Касымова",
            middleName: "Улукбековна",
            dateOfBirth: new Date("1995-01-14"),
            gender: "female",
            address: "г. Бишкек, ул. Московская 234",
            phone: "+996559874123",
            email: "saltanat.kasym@outlook.com",
            insuranceNumber: "INS369258",
            bloodType: "O-",
            allergies: "Латекс",
            chronicDiseases: "Нет",
        },
        {
            firstName: "Эркин",
            lastName: "Мамбетов",
            middleName: "Усенович",
            dateOfBirth: new Date("1973-08-12"),
            gender: "male",
            address: "г. Токмок, ул. Советская 67",
            phone: "+996554126789",
            email: "erkin.mambetov@mail.kg",
            insuranceNumber: "INS852741",
            bloodType: "AB-",
            allergies: "Сульфаниламиды",
            chronicDiseases: "Язвенная болезнь",
        },
    );

    const [record1, record2, record3, record4] = await MedicalRecord.create(
        {
            patient: patient1._id,
            doctor: doc_1._id,
            visitDate: new Date("2024-10-01T10:00:00Z"),
            symptoms: "Боль в груди, головокружение",
            diagnosis: "Гипертонический криз",
            notes: "Назначены препараты для снижения давления, повторный приём через неделю",
            recordNumber: "MR-1",
            createdBy: doc_1._id,
            updatedBy: doc_1._id,
        },
        {
            patient: patient2._id,
            doctor: doc_2._id,
            visitDate: new Date("2024-11-15T14:30:00Z"),
            symptoms: "Боль в правом колене после травмы",
            diagnosis: "Растяжение связок",
            notes: "Назначено МРТ, временно ограничить нагрузку",
            recordNumber: "MR-2",
            createdBy: doc_2._id,
            updatedBy: doc_2._id,
        },
        {
            patient: patient3._id,
            doctor: doc_2._id,
            visitDate: new Date("2025-01-20T09:00:00Z"),
            symptoms: "Одышка, быстрая утомляемость",
            diagnosis: "Анемия",
            notes: "Назначены анализы крови, препараты железа",
            recordNumber: "MR-3",
            createdBy: doc_2._id,
            updatedBy: doc_2._id,
        },
        {
            patient: patient1._id,
            doctor: doc_1._id,
            visitDate: new Date("2025-03-05T16:00:00Z"),
            symptoms: "Ушиб локтя",
            diagnosis: "Без повреждений кости, легкая гематома",
            notes: "Назначен холод и покой на 2-3 дня",
            recordNumber: "MR-4",
            createdBy: doc_1._id,
            updatedBy: doc_1._id,
        }
    );

    await Treatment.create(
        {
            medicalRecord: record1._id,
            patient: patient1._id,
            type: 'medication',
            name: 'Эналаприл',
            description: 'Препарат для снижения давления',
            dosage: '10мг',
            frequency: '2 раза в день',
            duration: '7 дней',
            startDate: new Date("2024-10-02"),
            endDate: new Date("2024-10-09"),
            status: 'completed',
            assignedBy: doc_1._id,
            updatedBy: doc_1._id,
        },
        {
            medicalRecord: record2._id,
            patient: patient2._id,
            type: 'procedure',
            name: 'МРТ колена',
            description: 'Магнитно-резонансная томография правого колена',
            startDate: new Date("2024-11-17"),
            status: 'scheduled',
            assignedBy: doc_2._id,
            updatedBy: doc_2._id,
        },
        {
            medicalRecord: record3._id,
            patient: patient3._id,
            type: 'medication',
            name: 'Феррум Лек',
            description: 'Препарат железа при анемии',
            dosage: '1 таблетка',
            frequency: '1 раз в день',
            duration: '1 месяц',
            startDate: new Date("2025-01-22"),
            endDate: new Date("2025-02-22"),
            status: 'in-progress',
            assignedBy: doc_2._id,
            updatedBy: doc_2._id,
        },
        {
            medicalRecord: record4._id,
            patient: patient1._id,
            type: 'recommendation',
            name: 'Покой и холод',
            description: 'Прикладывать лёд, избегать нагрузки',
            startDate: new Date("2025-03-06"),
            status: 'completed',
            assignedBy: doc_1._id,
            updatedBy: doc_1._id,
        }
    );
    await db.close();
};

run().catch(console.error);